# Generated by Django 3.1.7 on 2021-03-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_whole_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whole_comment',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
